### ISSUE TITLE
URL to ninja build system is broken

### ISSUE THREAD

**Issue by dongahn** [PRUNERS/archer#15]
For some reason, https://martine.github.io/ninja reference used in README.md is broken. Didn't know what should be the alternative so I couldn't do a PR.

**Comment by simoatze** [comment]
@dongahn why is "martine.github.io"?

**Comment by dongahn** [comment]
It is listed in the Prerequisite section of our README.md.

**Comment by simoatze** [comment]
@dongahn Sorry I was thinking at our Ninja tool haha, that's the Ninja build system and looks like they changed url, I'll fix it! Thanks!

**Comment by dongahn** [comment]
Yeah... their Ninja not our Ninja :-)
