### ISSUE TITLE
Warning of "unused linker flags" when compiling with Archer

### ISSUE THREAD

**Issue by simoatze** [PRUNERS/archer#17]
@lee218llnl Hey Greg, in the clang-archer wrapper the configuration allows to insert the correct rpath, etc. However when we use the wrapper to compile a file the .o we get the warning:

```
clang-3.9: warning: -Wl,-rpath=/home/simone/usr/lib: 'linker' input unused
clang-3.9: warning: argument unused during compilation: '-L/home/simone/usr/lib'

```

because we are not linking yet. Do you know a way how to avoid this? Checking for the `-c` flag and put an if-then-else inside the wrapper would be enough?

Thanks!

**Comment by lee218llnl** [comment]
@simoatze I have a fix for this. Should I submit a pull request to the master branch or the towards_tr4 branch?

**Comment by simoatze** [comment]
That would be great, thanks Greg!

**Comment by dongahn** [comment]
Probably to the master.
