### ISSUE TITLE
New branch "manage_clock" failing tests

### ISSUE THREAD

**Issue by simoatze** [PRUNERS/archer#20]
@jprotze Not sure if you saw it but your new branch is failing the tests, if you join to Salck (https://pruners.slack.com/messages/archer-travisci/) you'll see the TravisCI channel for Archer, anyway here's the link: https://travis-ci.org/PRUNERS/archer/builds/203203366.

**Comment by jprotze** [comment]
This branch depends on modified compiler-rt:
https://github.com/PRUNERS/compiler-rt/tree/manage_clock

How do I deactivate travis for this branch?

**Comment by simoatze** [comment]
I see, I'll take a look, no worries for now.

**Comment by jprotze** [comment]
New approach should deliver better results and uses only upstream TSan annotations
Tests run "successful"
