### ISSUE TITLE
Suppression for libarcher.sa

### ISSUE THREAD

**Issue by simoatze** [PRUNERS/archer#21]
Suppression for libomp.so and libarcher.so is made by the function  in "__tsan_default_suppressions" or through a file declared using the TSAN_OPTION. In branch manage_clock the suppression.txt has been updated but we need to update also the function redefined automatically by clang-archer at compile time. Also the suppression.txt suppress ompt_tsan.so, however the new name should be libarcher.so.

**Comment by simoatze** [comment]
@dongahn Why this issue wasn't closed automatically? I put Resolve #21 in pull request body message (#19).

**Comment by jprotze** [comment]
I reallized, that this suppression was the cause for additional memory overhead. So, I reverted this change.

**Comment by dongahn** [comment]
Hmmm. I dont understand this one. The keywords are documented at help.github.com/articles/closing-issues-via-commit-messages

And yours seem right.

**Comment by simoatze** [comment]
@jprotze So you basically don't need to suppress libarcher.so?

**Comment by dongahn** [comment]
Perhals automatic closing just works when the changes makes into the default branch (master...)

**Comment by jprotze** [comment]
@simoatze suppression for libarcher is not needed.

**Comment by simoatze** [comment]
@jprotze So can I also modify the archer Pass and remove the redefinition of the tsan suppression function? Or do we still need the suppression?

**Comment by jprotze** [comment]
You can remove the suppression also from the archer pass
