### ISSUE TITLE
Archer wrappers don't link against libarcher.so automatically

### ISSUE THREAD

**Issue by simoatze** [PRUNERS/archer#23]
@jprotze pointed out that we have always to manually add -larcher when linking a program compiled with Archer. It is necessary to modify the Archer wrapper to add the libarcher libarary when using the OMPT support version.

**Comment by dongahn** [comment]
Sounds good to me.

**Comment by dongahn** [comment]
I guess the resolve keyword is gone from the last commit msg... closing.

**Comment by simoatze** [comment]
In the guide it says that the keyword needs to be in the body of the pull request. I don't understand.
