### ISSUE TITLE
missing counter.cpp in Archer/rtl

### ISSUE THREAD

**Issue by peihunglin** [PRUNERS/archer#27]
Cmake reports missing counter.cpp in rt/CMakeLists.txt when building ROSE with llvm release_40.  
Is there any restriction for that?

**Comment by simoatze** [comment]
@peihunglin I already messaged @jprotze I think we just just forget to add it in the last commit.

**Comment by jprotze** [comment]
@peihunglin forgot to include the file in the last commit. It is commited now
