### ISSUE TITLE
archer webpage URL broken

### ISSUE THREAD

**Issue by dongahn** [PRUNERS/archer#5]
I have trouble viewing -- https://pruners.github.io/archer 

It may have something to do with moving the organization name to PRUNERS from PRUNER? 

![screen shot 2017-01-27 at 2 40 16 pm](https://cloud.githubusercontent.com/assets/862123/22390203/8eb39440-e49e-11e6-976a-24a25ffdf509.png)

**Comment by simoatze** [comment]
@dongahn The page of archer has not been created yet, I am going to update the entire website next week.

**Comment by dongahn** [comment]
Ah. Sorry.
