### ISSUE TITLE
Assertion fail on OpenMP runtime

### ISSUE THREAD

**Issue by simoatze** [PRUNERS/archer#51]
Two tests (task-two and parallel-reduction-nowait) are failing because of:

OMP: Error #13: Assertion failure at kmp_sched.cpp(85).

**Comment by simoatze** [comment]
@jprotze do you have any idea why?

**Comment by jprotze** [comment]
Yes, to provide a conforming implementation, we had to introduce compiler support. With old compilers, the flag is not set with a valid value, which results in the assert.
There is a deprecated-workshare branch, that changes this assert to a warning about an outdated compiler.

**Comment by dongahn** [comment]
Can we cherry-pick that?

**Comment by jprotze** [comment]
I'm currently pushing this patch to upstream (I guess it will land in the next few days):
https://reviews.llvm.org/D39890

Until then, you can simply use the branch for testing: https://github.com/OpenMPToolsInterface/LLVM-openmp/tree/deprecated-workshare

@simoatze : With that fix in upstream LLVM, you can switch to the upstream LLVM/OpenMP runtime.

**Comment by simoatze** [comment]
@jprotze Thanks! I tried the deprecated-workshare and it passes all the tests.
I'll switch to the upstream LLVM/OpenMP and do more tests.

**Comment by jprotze** [comment]
The patch landed in upstream llvm/OpenMP about an hour ago.
