### ISSUE TITLE
Removing OMPT tests

### ISSUE THREAD

**Issue by simoatze** [PRUNERS/archer#57]
@jprotze what do you think about removing the OMPT tests from archer tests now that OMPT is officially integrated in the OpenMP runtime?
I finished porting archer to clang 6.0 and I am ready to commit, but I get some OMPT test fails because most likely they need to be updated.
We don't really need to test OMPT in archer, do you agree?

**Comment by jprotze** [comment]
From my point of view, it makes sense to test the parts of OMPT where we rely on specific OMPT behavior/OpenMP semantics for the archer runtime.
I would agree if the tool is strictly coupled to a specific runtime. But if you want to combine Archer with a different openmp runtime, these tests can give a first hint if something is wrong.

I guess we can easily fix the broken tests, by comparing the tests with the tests that come with the LLVM/OpenMP runtime.

**Comment by simoatze** [comment]
@jprotze Good points. I will update the tests and start a new PR. The new version includes also a flag to disable static analysis from the command line (@dong).
