### ISSUE TITLE
Adopting a branching model

### ISSUE THREAD

**Issue by zvonimir** [PRUNERS/archer#59]
We found it useful in more extensive projects to adopt a branching model to follow, and in particular I like this one: http://nvie.com/posts/a-successful-git-branching-model/
In short, all the action is happening in the develop branch, and you only merge into master before doing a release. Just a thought.

**Comment by simoatze** [comment]
Yeah that is a good idea, once we merge the last changes I'll create a dev branch so we can keep working on that one. Thanks for the suggestion!

**Comment by simoatze** [comment]
This is done!
